version: "3.5"

services:
  db:
    container_name: db
    image: postgres:alpine
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./pgdata:/var/lib/postgres/data
    ports:
      - ${POSTGRES_PORT}:5432/tcp

  backend:
    container_name: backend
    build:
      context: ./backend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db